name:                Head-eq
version:             0.1.0.0
github:              "mino2357/Head-eq"
license:             BSD3
author:              "mino2357"
maintainer:          "mino2357@gmail.com"
copyright:           "Copyright (c) 2017 mino2357"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/mino2357/Head-eq#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  Head-eq-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Head-eq
    - repa

tests:
  Head-eq-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Head-eq
    - repa
